# Generated by Django 5.1.1 on 2024-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('biography', 'Biography'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('thriller', 'Thriller')], db_index=True, default='fiction', max_length=20, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(db_index=True, verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(db_index=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(db_index=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
